-- 墨记 study_blog 建表语句
-- 在库 study_blog 中执行

CREATE TABLE IF NOT EXISTS posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文章 ID',
  title VARCHAR(120) NOT NULL COMMENT '标题',
  summary VARCHAR(240) NOT NULL DEFAULT '' COMMENT '摘要',
  content MEDIUMTEXT NOT NULL COMMENT '正文',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='博客文章';
